---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: tiny-hat
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - asus-linux.repo # installs ~/files/rpm-ostree/asus-linux.repo
    install:
      - asusctl
      - asusctl-rog-gui
      - supergfxctl

    remove:
      - nvtop
      - htop
      - gnome-tour

  - type: default-flatpaks
    system:
      install:
        - com.valvesoftware.Steam
        - com.discordapp.Discord
        - dev.zed.Zed
        - com.github.tchx84.Flatseal

  - type: signing
