---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: tiny-hat
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 41

modules:
  - type: files
    files:
      - source: system
        destination: /

  # - type: brew
  #   brew-analytics: false
  #   auto-update: true
  #   auto-upgrade: true
  #   nofile-limits: true

  - type: rpm-ostree
    remove:
      - firefox
      - firefox-langpacks
      - nvtop
      - htop
      - gnome-tour
      - gnome-help

  - type: default-flatpaks
    notify: true
    system:
      install:
        - app.zen_browser.zen
        - com.valvesoftware.Steam
        - dev.zed.Zed

  - type: signing
