---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: tiny-hat
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 41

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - asus.repo # installs ~/files/rpm-ostree/asus.repo
    install:
      - asusctl
      - supergfxctl

    remove:
      - firefox
      - firefox-langpacks
      - nvtop
      - htop
      - gnome-tour

  - type: default-flatpaks
    system:
      install:
        - app.zen_browser.zen
        - com.valvesoftware.Steam
        - com.discordapp.Discord
        - dev.zed.Zed

  - type: signing
