---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: tiny-hat
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: brew
    brew-analytics: false
    auto-update: true
    auto-upgrade: true
    nofile-limits: true

  - type: rpm-ostree
    remove:
      - firefox
      - firefox-langpacks
      - nvtop

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox
        - com.valvesoftware.Steam
        - dev.zed.Zed

  - type: signing
