---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: tiny-hat
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - asus-linux.repo
      - asus-kernel.repo
    install:
      - asusctl
      - supergfxctl
      - kernel-rog-cachyos
      - kernel-rog-cachyos-devel-matched

    remove:
      - nvtop
      - htop
      - gnome-tour
  
  - type: akmods
    nvidia: true
    install: 
      - nvidia

  - type: default-flatpaks
    system:
      install:
        - com.valvesoftware.Steam
        - com.discordapp.Discord
        - dev.zed.Zed
        - com.github.tchx84.Flatseal

  - type: signing
